"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import localFont from "next/font/local";
import "./globals.css";
import SidebarPanel from "../component/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const [user, setUser] = useState(false);

  useEffect(() => {
    const details = localStorage.getItem("userDetails");

    if (!details) {
      router.push("/auth/login");
    } else {
      setUser(true);
    }
  }, [router]);

  return (
    <html lang="en">
      <body className={`${user ? "grid grid-cols-12" : ""}`}>
        <div className={`${user ? "col-span-2" : ""}`}>
          {user && <SidebarPanel />}
        </div>
        <div className={`${user ? "col-span-10" : ""}`}>{children}</div>
      </body>
    </html>
  );
}
